### ISSUE TITLE
"too many open files" on MacOS

### ISSUE THREAD

**Issue by Ptival** [vlaci/nix-doom-emacs#387]
Not sure you can do much about it, but I can't seem to install doom-emacs via home-manager on NixOS.

I keep getting:
```
error: opening directory '/nix/store/qzcy2dq1fba86d34k0d6apdirkxkxnp7-source': Too many open files
```

Possibly related:
https://github.com/NixOS/nixpkgs/issues/101459

**Comment by Eason0210** [comment]
I install Nix, and got the same error on MacOS. Any one known how to fix it?

**Comment by sveitser** [comment]
I was able to move past that by increasing the maximum number of open files in [this way](https://discussions.apple.com/thread/253001317?answerId=255632520022#255632520022)

However it seems this applies too late in the boot process and I still need to restart the `nix-daemon` via `sudo launchctl stop org.nixos.nix-daemon` once after each reboot.

**Comment by Eason0210** [comment]
I have fixed this with install `nix-darwin` before activate my nix-config.   It is not related to `nix-doom-emacs`, sorry!

**Comment by nckrse** [comment]
> I was able to move past that by increasing the maximum number of open files in [this way](https://discussions.apple.com/thread/253001317?answerId=255632520022#255632520022)
> 
> However it seems this applies too late in the boot process and I still need to restart the `nix-daemon` via `sudo launchctl stop org.nixos.nix-daemon` once after each reboot.

+1

Experienced this issue and raised file/proc limits via shell/plist and did not resolve until I restarted the nix-daemon. Thank you!
