### ISSUE TITLE
Derivation failed when using emacsGcc

### ISSUE THREAD

**Issue by Catvert** [vlaci/nix-doom-emacs#57]
Hi !
I've been trying to get emacsGcc to work for several hours. Each time, the derivation fails. 
Here is my module : 
```nix
let
  emacs-overlay = builtins.fetchTarball "https://github.com/nix-community/emacs-overlay/archive/master.tar.gz";
  pkgs = import <nixpkgs> { overlays = [ (import emacs-overlay) ]; };
  nix-doom-emacs = builtins.fetchTarball "https://github.com/vlaci/nix-doom-emacs/archive/master.tar.gz";
in 
  with pkgs; callPackage nix-doom-emacs {
    bundledPackages = false;
    emacsPackages = emacsPackagesFor emacsGcc;
    doomPrivateDir = ./doom.d;
  }
```
note that when I use the emacs or emacsUnstable package, there is no issue.

Here is logs when I 'home-manager switch' : https://pastebin.com/4tkU8dTe
Here is my init.el : https://pastebin.com/w1qNyW6e (note that I also tried with all options disabled and I have the same issue).

Thanks for your help !

**Comment by vlaci** [comment]
I have not tried `emacsGcc` before. Looking into it now.

**Comment by vlaci** [comment]
So yeah, it fails for me too with a 255 exit code without any helpful error message. Sigh, it won't be easy to track down :)

**Comment by vlaci** [comment]
I have pushed a new revision onto the `develop` branch which seems to work for me for a minimal `init.el` file. Unfortunately the build process is not cached well so any changes in the packages to be installed results in the recompilation of all `.eln` files.

**Comment by Catvert** [comment]
Thank you for your quick reply! Unfortunately, I still have the same problem, the /homeless-shelter issue, which should have been resolved in your last commit of the develop branch (89fc9ed07f). Do you think I made a manipulation mistake? When I tried your commit, I first cleaned up my installation in order to recompile emacsGcc from scratch.

Here is what my module looks like : 
```nix
let
  emacs-overlay = builtins.fetchTarball "https://github.com/nix-community/emacs-overlay/archive/master.tar.gz";
  pkgs = import <nixpkgs> { overlays = [ (import emacs-overlay) ]; };
  nix-doom-emacs = builtins.fetchTarball "https://github.com/vlaci/nix-doom-emacs/archive/89fc9ed07fc8515e58ab80b3bad2abbdb02a9ba4.tar.gz";
in 
  with pkgs; callPackage nix-doom-emacs {
    bundledPackages = false;
    emacsPackages = emacsPackagesFor emacsGcc;
    doomPrivateDir = ./doom.d;
  }
```
and here is the end of the logs during my compilation from 0 : https://pastebin.com/1h4eR74C

**Comment by vlaci** [comment]
Interestingly I haven't got a permission issue in this build stage. Will try again with your config now.

**Comment by vlaci** [comment]
I have used `emacs-overlay` from a previous commit for my tests: https://github.com/nix-community/emacs-overlay/archive/585e07a72aa50c06c523fc6037bb13441bd5c47b.tar.gz

I'll look into it more why the new revision fails.

**Comment by vlaci** [comment]
So latest version of gccEmacs would write some `.eln` files and does not respect the value of `comp-deferred-compilation` everywhere. If I workaround the issue by making a writable `$HOME`, it crashes later during build for me.

**Comment by vlaci** [comment]
The updated commit works fine for me with the latest emacs-overlay revision (7505f2bc3f25977a1963ac90705b729abe36437f).

I am curious if the issue crashing the build for me is present in vanilla doom + gccEmacs...

**Comment by vlaci** [comment]
Unfortunately more complex builds still stall on emacs-overlays newer than d9e6c250 and hence gccEmacs newer than e542b4b7 :(

**Comment by vlaci** [comment]
so the "good" news is, that the build hangs the same way (builder processes crash) using a vanilla doom checkout.

**Comment by vlaci** [comment]
Finally I was able to build using the latest gccEmacs sources:

```nix
# default.nix
let
  emacs-overlay = builtins.fetchTarball "https://github.com/nix-community/emacs-overlay/archive/master.tar.gz";
  pkgs = import <nixpkgs> { overlays = [ (import emacs-overlay) ]; };
  nix-doom-emacs = ./.;
in 
  with pkgs; callPackage nix-doom-emacs {
    bundledPackages = false;
    emacsPackages = emacsPackagesFor (emacsGcc.overrideAttrs (super: {
      patches = super.patches ++ [ ./gccemacs.patch ];
    }));
    doomPrivateDir = ./doom.d;
  }
```

```patch
# gccemacs.patch
diff --git a/lisp/emacs-lisp/comp.el b/lisp/emacs-lisp/comp.el
index cac63a5978..6b7616ccba 100644
--- a/lisp/emacs-lisp/comp.el
+++ b/lisp/emacs-lisp/comp.el
@@ -2597,7 +2597,7 @@ Return the its filename if found or nil otherwise."
 ;;;###autoload
 (defun comp-subr-safe-advice (subr-name)
   "Make SUBR-NAME effectively advice-able when called from native code."
-  (unless (or (memq subr-name comp-never-optimize-functions)
+  (unless (or t (memq subr-name comp-never-optimize-functions)
               (gethash subr-name comp-installed-trampolines-h))
     (let ((trampoline-sym (comp-trampoline-sym subr-name)))
       (cl-assert (subr-primitive-p (symbol-function subr-name)))

```

The issue came up when the advising machinery got introduced in gccEmacs. Still don't know if it is an issue in doom or emacs itself.

**Comment by vlaci** [comment]
For the record https://github.com/hlissner/doom-emacs/issues/3983

**Comment by Catvert** [comment]
Hey !
It works! Many thanks for your involvement and your speed in mitigating this problem. My emacs is faster than ever :D !

I will continue to follow this issue and the one you have opened on doom-emacs repo.

Btw, I have theses warnings in Emacs :
```
Warning (comp): No write access for /nix/store/zkkrjwgqydw2a36a4vras95igp4fi8y8-straight-emacs-env/cache/eln/28.0.50-x86_64-pc-linux-gnu-e5719e96d93ad8f9231db9979847f082/mule-util-429a54e3cf57581d2babee3f02f281a3-be57bb5ae5733a27b3de302d7e81e7bc.eln skipping. Disable showing Disable logging
Warning (comp): No write access for /nix/store/zkkrjwgqydw2a36a4vras95igp4fi8y8-straight-emacs-env/cache/eln/28.0.50-x86_64-pc-linux-gnu-e5719e96d93ad8f9231db9979847f082/mule-util-429a54e3cf57581d2babee3f02f281a3-be57bb5ae5733a27b3de302d7e81e7bc.eln skipping. Disable showing Disable logging
Warning (comp): No write access for /nix/store/zkkrjwgqydw2a36a4vras95igp4fi8y8-straight-emacs-env/cache/eln/28.0.50-x86_64-pc-linux-gnu-e5719e96d93ad8f9231db9979847f082/mule-util-429a54e3cf57581d2babee3f02f281a3-be57bb5ae5733a27b3de302d7e81e7bc.eln skipping. Disable showing Disable logging
Warning (comp): No write access for /nix/store/zkkrjwgqydw2a36a4vras95igp4fi8y8-straight-emacs-env/cache/eln/28.0.50-x86_64-pc-linux-gnu-e5719e96d93ad8f9231db9979847f082/mule-util-429a54e3cf57581d2babee3f02f281a3-be57bb5ae5733a27b3de302d7e81e7bc.eln skipping. Disable showing Disable logging

... (lots of similar lines)
```
I think it's quite normal, but I'm still asking you the question to know if it doesn't have any incident on the compilation of the el files.

Have a great day !

**Comment by vlaci** [comment]
Hmm, I think adding a writable location in your configuration should mitigate the issue. I have pushed a change for that. LEt me know if it mitigates your issue.

**Comment by Catvert** [comment]
That doesn't seem to have solved the problem :/
I still have these warning : https://pastebin.com/v2Dirzsy (I removed a few lines to respect the 512kb pastebin limit).
This significantly slows down the time it takes before Emacs is up and running, even for evil to work at all.

**Comment by vlaci** [comment]
Interestingly I don't have this issue at all.

- Are you on the latest revision?
- Do any `eln` files exist under `/nix/store/yz5lqjx94d59wi4fbydijbbmihlgnjzz-straight-emacs-env/cache/eln/28.0.50-x86_64-pc-linux-gnu-e5719e96d93ad8f9231db9979847f082/` ?
- Do the files mentioned by the error message exist?

**Comment by Catvert** [comment]
I had the 'comp-deferred-compilation' variable enabled in my configuration, when I disabled it, I don't have the problem anymore. It should not be enabled since the compilation of the elc files seems to happen directly during the installation (if I'm not mistaken). Also, for any change in my config.el file, a full recompilation of the elc files seems to happen (which takes a lot of time on my machine). Is it possible to disable this recompilation (except when I edit the init.el or packages.el files) ?

Thanks to you!

**Comment by vlaci** [comment]
Yeah, doom initate a full compilation at install time. Contents of ".doom.d" (`init.el`, `config.el` and `packages.el`) are populated before build. Although I don't know if changes in `config.el` can affect the build output or not. `init.el` and `packages.el` obviously affects the build through the packages they provide.
I could come up with a way to inject `config.el` later in the build process, after `doom install` completes. That way changes in it won't cause `doom install` to run. But I am not sure if it is a good idea.

In the meantime you can inject additional customizations through the `extraConfig` parameter. Its content is appended at the end of `config.el`. It should not cause a full rebuild.

**Comment by Catvert** [comment]
Perfect ! I will use emacsGcc intensively for some time and report back to you if I have problems.

**Comment by Catvert** [comment]
Hey !
I've tried to use the same module on my laptop but I have a rather strange error when I start emacs (I don't have this problem on my desktop pc even though I use exactly the same versions). Doom doesn't even load (the vanilla is just showing) with an error on the status bar : 
```
Invalid function: ((bytecomp "(setf seq-elt) is already defined as something else than a generic function" :error "*Compile-Log*"))
```

Knowing, that I had already tried to install emacsGcc on this pc before you offered me the gccemacs.patch.
Emacs is completely recompiled from 0, but it looks like there are 'leftovers' that were not removed with the collect-garbage, resulting in this error.

Thanks for your help!

**Comment by purcell** [comment]
Just in case anyone else finds this issue via Googling the error message, I found that I can resolve it by deleting the `~/.emacs.d/eln-cache` directory, so I guess it's a result of some mangled cache files that might get re-used between development versions and therefore clash.
